# Results

## Grain yield

In Reckenholz, the most productive location, median grain yields of the pure fertilised oat stands ranged between 4.9 and 5.4 tha^-1^. Pure NLL stands produced 2.8 – 3.6 tha^-1^, while the oat NLL mixtures reached 3.7–4.8 tha^-1^ of total yield (Figure 2). Gross Lüsewitz and Seegräben exhibited similar yields to Reckenholz in pure fertilised oat stands, however, the NLL yields and total yields were lower in Gross Lüsewitz (p < 0.001). Reckenholz and Seegräben exhibited the highest NLL yields in pure stands compared with the other locations (p < 0.001). The total yields of Bad Vilbel and Novi Sad were lower across all observed treatments in the year 2022 than the total yields of Reckenholz, Seegräben or Gross Lüsewitz (p < 0.001), whereas in 2023, only the total yield of Gross Lüsewitz was significantly lower than the yields recorded in Novi Sad, Reckenholz and Seegräben (Supplemental materials - Table S3). Further, the yields of all NLL and oat varieties in pure stands (p < 0.001) and the partial yields of Jowisz × Troll in mixed stands differed significantly (p < 0.05). Across all locations the averaged yields of pure NLL and oat stands were not significantly different from the averaged yields across all mixtures. Regarding the proportion of the partial NLL yield in mixtures, Bad Vilbel and Seegräben exhibited higher NLL than oat proportions of 62% and 59% across all years, respectively, whereas the proportions of the NLL yield in mixtures amounted to 35%, 29% and 24% in Gross Lüsewitz, Novi Sad and Reckenholz, respectively (p < 0.001). A strong year effect was apparent, resulting in an elevated proportion of the NLL yield by 16% in 2022 and 7% in 2023 across all mixtures, respectively. Additionally, an oat-interaction effect could be detected, resulting in an increased NLL proportion by 5% if the NLL were mixed with Troll, and a decreased proportion by -4.6% if the NLL were mixed with Lion. All locations exhibited strong year-by-year variation of the NLL proportion (Supplemental materials - Appendix A).

![Grain yield overview of pure and mixed stands by location and the location's country code in brackets. Fertilised oats are shown in yellow-brown hues. For all graphs, the median value is represented by the bar height, and the variability (median absolute deviation) by the error bars. In mixed stands, the lower bar represents the partial lupin values, the upper bar the partial oat values.](/writing/pictures/yieldplot.png){#fig-des width=100%}

## Grain-yield performance assessment
The land equivalent ratio (LER_N) assessed across all locations with regards to fertilised oats as pure stands, years and treatments did not differ from unity (LER_N = 1) on a treatment, nor location level (Supplemental materials - Appendix A). Additionally, no significant difference could be detected between any pairs of mixed stand treatments or pairs of locations. Though the land equivalent ratio (LER) with regards to unfertilised oats was higher than the LER_N, it still did not differ significantly from unity (LER = 1).
The total CPR with regards to fertilised and unfertilised oats as reference pure stands was elevated above unity (E = 2) for all mixed stands, in absence of any treatment effect, amounting to CPR = 5.3 on average (p < 0.001), and CPR_N = 4.6 (p < 0.001), respectively, driven by the high oat CPR (Supplemental materials - Appendix A). The CPR_N was significantly lower than the recorded CPR in all mixed treatments but Troll × Lunabor and Troll × Jowisz (p < 0.05). None of the CPR or CPR_N values exhibited significant differences between treatments across all locations and years. Similar to the total CPR, the CPR_oat was above unity (E = 1) in both cases, with regards to fertilised (CPR_oat_N) and unfertilised (CPR_oat) oats as pure reference stands (p < 0.001). The CPR_oat was significantly larger than the CPR_oat_N for all mixed Bison and Lion treatments (p < 0.05), whereas the mixed Troll treatments were agnostic to the fertilisation regime of their pure reference stands. Post-hoc comparisons unveiled significantly higher CPR_oat and CPR_oat_N in three cases of Lion, compared to Troll, where Lion has shown a CPR exceeding the Trolls CPR by 0.8 - 0.9 (p < 0.01). However, these effects were restricted to specific mixed cropping comparisons (e.g. Lion × Probor compared to Troll × Probor) but did not hold true globally for both oat varieties across all paired mixtures. Conversely to the CPR of oats and the total CPR, the CPR of NLLs did not differ significantly from unity (E = 1), nor were any variety, location or year effects apparent.

## Grain-yield stability
### Static grain-yield stability
The static grain-yield stability, expressed as the coefficient of variation (CV) calculated on a treatment basis across all environment-years unveiled no significance differences in the coefficient of variation across partial NLL, oat yields or the total yield (Table 3). However, trends are visible for the yield dispersion compared to the treatments' mean yield, the dispersion is larger in pure stands of NLLs and some mixed stands, relative to the majority of the mixed stands and pure (un-)fertilised oat stands. Further, fertilised and unfertilised oats did not differ significantly with regards to their CV.

::: {.table-caption #tbl-overview}
Overview table across the grain-yield stability metrics summarised across all locations on a treatment basis. CV = Coefficient of variation, $b_{1}$ = Finlay–Wilkinson slope, $S^2_{di}$ = Eberhart–Russell deviation variance, WAAS = weighted average of absolute scores. Letters correspond to the significance grouping of the pair-wise post-hoc tests (p < 0.05) adapted for multiple testing.
:::
| Treatment       |CV total yield     |$b_{1}$ (responsiveness)| $S^2_{di}$ (dispersion) |WAAS (sensitivity)|
|----------------:|------------------:|------------------:|-----------------:|----------------:|
|  Bison          |  17 <sup>a</sup>  |0.68<sup>a</sup>   | 0.24<sup>a</sup> |0.66<sup>a</sup> |
|  Lion           |  16 <sup>a</sup>  |0.63<sup>a</sup>   | 0.14<sup>a</sup> |0.58<sup>a</sup> |
|  Troll          |  17 <sup>a</sup>  |0.57<sup>a</sup>   | 0.3 <sup>a</sup> |0.80<sup>a</sup> |
|  Bison_N        |  18 <sup>a</sup>  |1.1 <sup>a</sup>   | 0.21<sup>a</sup> |0.35<sup>a</sup> |
|  Lion_N         |  16 <sup>a</sup>  |1.14<sup>b</sup>   | 0.05<sup>b</sup> |0.08<sup>b</sup> |
|  Troll_N        |  15 <sup>a</sup>  |1.2 <sup>a</sup>   | 0.09<sup>a</sup> |0.15<sup>b</sup> |
|  Lunabor        |  31 <sup>a</sup>  |0.95<sup>a</sup>   | 0.22<sup>a</sup> |0.44<sup>a</sup> |
|  Probor         |  35 <sup>a</sup>  |1.05<sup>a</sup>   | 0.23<sup>a</sup> |0.48<sup>a</sup> |
|  Jowisz         |  27 <sup>a</sup>  |1.01<sup>a</sup>   | 0.19<sup>a</sup> |0.38<sup>a</sup> |
| Bison × Lunabor |  17 <sup>a</sup>  |1.08<sup>b</sup>   | 0.004<sup>b</sup>|0.11<sup>b</sup>|
| Bison × Probor  |  18 <sup>a</sup>  |0.98<sup>c</sup>   | 0.03<sup>b</sup> |0.04<sup>b</sup>|
| Bison × Jowisz  |  18 <sup>a</sup>  |0.91<sup>c</sup>   | 0.06 <sup>b</sup>|0.08<sup>b</sup>|
| Lion × Lunabor  |  15 <sup>a</sup>  |1.05<sup>b</sup>   | 0.03 <sup>b</sup>|0.21<sup>b</sup>|
| Lion × Probor   |  16 <sup>a</sup>  |1.14<sup>a</sup>   | 0.09 <sup>a</sup>|0.34<sup>a</sup>|
| Lion × Jowisz   |  15 <sup>a</sup>  |1.05<sup>b</sup>   | 0.01 <sup>b</sup>|0.1<sup>b</sup>|
| Troll × Lunabor |  17 <sup>a</sup>  |1.21<sup>b</sup>   | 0.03 <sup>b</sup>|0.2<sup>b</sup>|
| Troll × Probor  |  27 <sup>a</sup>  |1.23<sup>b</sup>   | 0.06 <sup>b</sup>|0.35<sup>a</sup>|
| Troll × Jowisz  |  24 <sup>a</sup>  |1.03<sup>b</sup>   | 0.0005<sup>b</sup>|0.067<sup>b</sup>|

### Dynamic grain-yield stability
The Finlay–Wilkinson regression coefficients ($b_{1}$) measuring the responsiveness of the total yield to environmental impact was significantly elevated ($b_{1}$ > 1) in pure stands of fertilised Lion, and the mixed stands of Bison × Lunabor, Lion × Lunabor, Lion × Jowisz and Troll × Probor, whereas Bison × Probor and Bison × Jowisz exhibited buffering capacity ($b_{1}$ < 1) to the environmental influence (p < 0.005). All pure stands of NLLs and oats, other than fertilised Lion, and the mixed stands of Lion × Probor and Troll × Jowisz exhibited average environmental responsiveness. The Eberhart–Russell deviation variance $S^2_{di}$ was highest in pure stands of NLLs, and lowest in mixed treatments (Table 3). The pure stand of fertilised Lion and Lion × Probor both combined high responsiveness $b_{1}$ with low $S^2_{di}$ dispersion, indicating that both treatments reliably and consistently respond to their environmental conditions.

![Recorded mean total yields plotted against their weighted average of absolute scores, which indicates the treatment's  sensitivity to environmental conditions. The yield × WAAS plot shows the results of the pure and mixed stands across the years 2022 - 2024 (2022 - 2023 for Swiss locations). Treatments placed in the top left quadrant exhibited the highest yields while showing the lowest environmental sensitivity and are thus most desireable. The dashed lines represent the median values of each axis. Treatments positioned further to the right exhibit lower grain-yield stability.](/writing/pictures/yieldxwaas.png){#fig-des width=100%}

The AMMI model unveiled two groups according to the WAAS-scores: the sensitivity to environmental conditions of pure stands of NLLs and oats was generally higher than that of mixed stands (Figure 3, Table 3), further the AMMI-Model unveiled significant location and treatment effects but no significant interaction thereof. The WAAS-scores indicated the mixture’s higher stabilities across all environment-years, due to their weaker sensitivity to the location effect. The WAAS-scores further showed, though not statistically significant, the higher stability of fertilised pure oat stands relative to the unfertilised pure oat stands. Across the assessed interaction principal components axes (IPCAs), IPCA1 distinguished between the two groups of locations Novi Sad and Gross Lüsewitz (negative loadings) versus Bad Vilbel, Reckenholz and Seegräben (positive loadings) (Figure 4). Additionally, IPCA1 clearly distinguished the pure stands of NLLs (positive loadings) from the oats (negative loadings). By contrast, IPCA2 distinguished the fertilised pure stands of oats (negative loadings) from the unfertilised pure stands of oats. With regards to the factor loading of IPC1 and IPC2, the two mixtures Lion × Jowisz and Lion × Jowisz plotted closest to the origin (0,0). These two treatments interacted least with the locations along IPCA1 and IPCA2, and were thus exhibiting a more stable performance across all five locations than treatments placing at higher euclidean distance to the origin (Supplemental materials - Table S4).

![The additive main effects and multiplicative interaction (AMMI) biplot of the treatment (circles) and location (triangles) scores on the first two interaction principal component axes for total grain yield in pure and mixed stands. The closer a treatment is positioned to the origin (x,y = 0, 0), the higher was its grain-yield stability. The following location acronyms were used: Gross - Gross Lüsewitz (2022 - 2024), Novi- Novi Sad (2022 - 2024), Vilbel - Bad Vilbel (2022 - 2024), Re - Reckenholz (2022 - 2023) and Seegr - Seegräben (2022 - 2023).](/writing/pictures/ammibiplot.png){#fig-des width=100%}
